name: Azure OIDC auth flow
description: "Azure OpenID Connect authentication flow"

inputs:
  client-id:
    description: "The Azure AD application client ID"
    required: true
  tenant-id:
    description: "The Azure AD tenant ID"
    required: true
  audience:
    description: "The audience for the access token"
    required: true

outputs:
  access-token:
    description: "The Azure OIDC bearer access token"
    value: ${{ steps.api-access.outputs.AZURE_ACCESS_TOKEN }}

runs:
  using: "composite"
  steps:
    - name: Azure OpenID Connect
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.client-id }}
        tenant-id: ${{ inputs.tenant-id }}
        audience: ${{ inputs.audience }}
        allow-no-subscriptions: true

    - name: OSMP API access
      id: api-access
      shell: bash
      run: |
        TOKEN=$(az account get-access-token --query 'accessToken' -o tsv --resource ${{ inputs.audience}})
        echo "AZURE_ACCESS_TOKEN=$(echo $TOKEN)" >> $GITHUB_OUTPUT
