name: No response

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: "5 * * * *"

permissions:
  contents: read

jobs:
  noResponse:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - uses: lee-dohm/no-response@main
        with:
          token: ${{ github.token }}
          responseRequiredLabel: needs-more-info
          daysUntilClose: 14
          closeComment: >
            This issue has been automatically closed due to no response from the original author.
            Please feel free to reopen it if you have more information that can help us investigate the issue further.
